### ISSUE TITLE
Crash when using Data Inspector

### ISSUE THREAD

**Issue by Duchex** [kosmtik/kosmtik#113]
When I turn Data Inspector on I get the following crash:

```
/home/penny/src/kosmtik/src/back/XRayTile.js:20
        vtile.parse();
              ^
TypeError: Object #<VectorTile> has no method 'parse'
    at XRayTile.render (/home/penny/src/kosmtik/src/back/XRayTile.js:20:15)
    at /home/penny/src/kosmtik/src/back/ProjectServer.js:139:19
```

**Comment by JesseCrocker** [comment]
This error is a mapnik-3.5 compatibility issue.

**Comment by Duchex** [comment]
Forgive the question, but is this something that I can fix by updating/changing packages or do I need to wait for a fix?

**Comment by nebulon42** [comment]
Closing per https://github.com/kosmtik/kosmtik/issues/113#issuecomment-203609793.
