### ISSUE TITLE
TypeError: Object #<VectorTile> has no method 'parse'

### ISSUE THREAD

**Issue by pnorman** [kosmtik/kosmtik#122]
When I turn on data inspector I get this

```
[httpserver] /osm-clear/poll/ 404

/home/pnorman/osm/kosmtik-3/src/back/XRayTile.js:20
        vtile.parse();
              ^
TypeError: Object #<VectorTile> has no method 'parse'
    at XRayTile.render (/home/pnorman/osm/kosmtik-3/src/back/XRayTile.js:20:15)
    at /home/pnorman/osm/kosmtik-3/src/back/ProjectServer.js:139:19
Segmentation fault (core dumped)
```

The project is a vector tile yml

**Comment by yohanboniface** [comment]
Which Mapnik and node versions?

**Comment by yohanboniface** [comment]
Also, which tool to serve the vector tile you are using?

**Comment by pnorman** [comment]
node-mapnik 3.5.12. I can't find mapnik-config in node_modules so not sure what mapnik version.

Node v0.10.25

I pointed Kosmtik directly at data.yml

**Comment by yohanboniface** [comment]
Can you try with mapnik3.5 branch? I'm about to merge it.

**Comment by yohanboniface** [comment]
Actually, merged, so just pull in and npm install again.

**Comment by pnorman** [comment]
Fixed
