### ISSUE TITLE
Vector Tile has POLYGON with first ring clockwise in X-Ray mode

### ISSUE THREAD

**Issue by pnorman** [kosmtik/kosmtik#125]
When I turn on X-Ray mode I get
```
Trace
    at ProjectServer.raise (/home/pnorman/osm/kosmtik-3/src/back/ProjectServer.js:239:13)
    at /home/pnorman/osm/kosmtik-3/src/back/ProjectServer.js:140:38
Vector Tile has POLYGON with first ring clockwise. It is not valid according to v2 of VT spec.
```
The tile which failed to load was in North America without any coastline and I was using water polygons

**Comment by yohanboniface** [comment]
Which vector tiles, still local ones, generated by kosmtik itself?

**Comment by springmeyer** [comment]
> Vector Tile has POLYGON with first ring clockwise. It is not valid according to v2 of VT spec.

In very rare cases this error may also occur due to a bug in node-mapnik. I recommend watching for the node-mapnik v3.5.13 release (due out later today) and testing again with that. So, the error is likely the tiles but upgrade to v3.5.13 to rule out https://github.com/mapbox/mapnik-vector-tile/pull/204

**Comment by yohanboniface** [comment]
OK, I'll upgrade asap, thanks.
@springmeyer how can we define the version of tiles we want to expose from carto?
This bug is raising while serving tiles from within kosmtik itself, but we are not forcing any version afaik.

**Comment by pnorman** [comment]
> Which vector tiles, still local ones, generated by kosmtik itself?

yes

**Comment by yohanboniface** [comment]
Or I'd expect to be able to define the spec version I'm claiming on [map.render](https://github.com/kosmtik/kosmtik/blob/master/src/back/Tile.js#L34) but I don't get it in the [doc](http://mapnik.org/node-mapnik/documentation/3.5/).
I'm certainly just too tired ;)

**Comment by springmeyer** [comment]
> @springmeyer how can we define the version of tiles we want to expose from carto?

You must have mean `from node-mapnik`? Either way, you cannot control the version at runtime. If you want to produce v1 tiles you would need to downgrade to node-mapnik 3.4.x. If you want to produce v2 tiles use node-mapnik >= 3.5.x.

**Comment by springmeyer** [comment]
> I recommend watching for the node-mapnik v3.5.13 release (due out later today)

It has now been published @yohanboniface

**Comment by yohanboniface** [comment]
Thanks, updated package.json, cc @pnorman

**Comment by pnorman** [comment]
Fixed
