### ISSUE TITLE
Cannot update kosmtik

### ISSUE THREAD

**Issue by cmyk** [kosmtik/kosmtik#131]
https://dl.dropboxusercontent.com/u/815924/bugs/kosmtik/npm-debug.log.zip

**Comment by pnorman** [comment]
With all nodejs problems, try `rm -rf node_modules/ && npm install` after updating.

**Comment by cmyk** [comment]
That's what I did it with in the first place.
Have you looked at the log? 
`Tried to download: https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.5.13/Release/node-v14-darwin-x64.tar.gz `

**Comment by yohanboniface** [comment]
@cmyk AFAIK there Node 0.12.x is no more supported by node-mapnik. Are you able to upgrade (maybe using NVM)?

**Comment by cmyk** [comment]
Okay, got it. Had to install node5. Node6 gave troubles as well. Thanks for the help!

**Comment by yohanboniface** [comment]
> Node6 gave troubles as well.

Yes, node-mapnik is not yet v6 ready (see https://github.com/mapnik/node-mapnik/issues/636). Joices of nodejs ;)
