### ISSUE TITLE
map extent out of [-180,180] is not rendered

### ISSUE THREAD

**Issue by Fil** [kosmtik/kosmtik#136]
`/earthquake/export/?showExtent=false&format=png&width=1000&height=560&scale=1&zoom=5&bounds=-193.97460937500003%2C59.55659188568175%2C-150.02929687500003%2C69.91521433690129`

creates a map where the part before -180 is gray.

![eeniftwb](https://cloud.githubusercontent.com/assets/7001/15271094/173bb670-1a39-11e6-9169-4ab6380ebc4b.png)

**Comment by pnorman** [comment]
In web mercator, there is nothing outside of [-180, 180]

**Comment by Fil** [comment]
You mean the Earth ain't flat? :-)

We still would like to export as PNG the map we see in the kosmtik interface (there it is not cut at -180).

**Comment by pnorman** [comment]
It is cut, but Leaflet renders another copy.

**Comment by Fil** [comment]
Indeed, this issue is that we would like to find a way to ask mapnik to render all the extent too.

(An alternative would be to render two PNGs and stitch them, which sounds clumsy.)

**Comment by nebulon42** [comment]
I don't think this is a Kosmtik but rather a Mapnik problem. I'm going to close, but feel free to re-open/convince me. :)
