### ISSUE TITLE
Build fails on Arch linux due to missing vector_tile_config.hpp

### ISSUE THREAD

**Issue by jokuNimi** [kosmtik/kosmtik#143]
When attempting to install the program on Arch linux, by following the readme and executing `npm install`, I get errors and the build fails. The relevant output seems to be
```
node-pre-gyp ERR! Tried to download: https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.5.13/Release/node-v48-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for mapnik@3.5.13 and node@6.2.0 (node-v48 ABI) (falling back to source compile with node-gyp) 
make: Entering directory '/home/valtteri/osm/kosmtik/node_modules/mapnik/build'
  ACTION binding_gyp_make_vector_tile_target_generate_setting Release/obj/gen/mapnik_settings.js
  COPY /home/valtteri/osm/kosmtik/node_modules/mapnik/lib/binding/node-v48-linux-x64/mapnik_settings.js
  TOUCH Release/obj.target/make_vector_tile.stamp
  CXX(target) Release/obj.target/mapnik/src/mapnik_logger.o
  CXX(target) Release/obj.target/mapnik/src/node_mapnik.o
../src/node_mapnik.cpp:2:34: fatal error: vector_tile_config.hpp: No such file or directory
 #include "vector_tile_config.hpp"
```
but I'll attach the entire log ([npm-debug-normal-user.log.txt](https://github.com/kosmtik/kosmtik/files/285610/npm-debug-normal-user.log.txt)). Running npm as root also fails but with different errors:
```
node-pre-gyp ERR! Tried to download: https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.5.13/Release/node-v48-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for mapnik@3.5.13 and node@6.2.0 (node-v48 ABI) (falling back to source compile with node-gyp) 
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/6.2.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/valtteri/osm/kosmtik/node_modules/mapnik/.node-gyp"
make: Entering directory '/home/valtteri/osm/kosmtik/node_modules/mapnik/build'
make: *** No rule to make target '../.node-gyp/6.2.0/include/node/common.gypi', needed by 'Makefile'.  Stop.
make: Leaving directory '/home/valtteri/osm/kosmtik/node_modules/mapnik/build'
gyp ERR! build error 
```
I'll attach that log as well ([npm-debug-root.log.txt](https://github.com/kosmtik/kosmtik/files/285611/npm-debug-root.log.txt)).

Mapnik, npm and node.js are all the newest version available from the arch repositories.

**Comment by yohanboniface** [comment]
node-mapnik can't be built yet on Node V6, see https://github.com/mapnik/node-mapnik/issues/636 and https://github.com/mapnik/node-mapnik/issues/634

When using NodeJS, I suggest using NVM (of Fin if you are on fish shell) to be able to take control over the used version.

FYI I'm no Arch too and it builds as soon as I don't use V6 ;)

Closing here because there is no action expected on our side.

**Comment by yohanboniface** [comment]
Side note: I suggest never ever using sudo with npm.
(And for global install of node modules, configure your `NPM_CONFIG_PREFIX`).
