### ISSUE TITLE
Readme has "insecure dependencies" badge

### ISSUE THREAD

**Issue by matkoniecz** [kosmtik/kosmtik#148]
see https://github.com/kosmtik/kosmtik#kosmtik

**Comment by nebulon42** [comment]
In theory that might be a concern, but since npm is specified as `^3.3.5` you will get `3.9.6` (the latest version) on a fresh install. See http://stackoverflow.com/a/22345808. However, the reference version should probably be updated.

**Comment by yohanboniface** [comment]
Back to green.
