### ISSUE TITLE
it is not clear how to set zoom level during export

### ISSUE THREAD

**Issue by matkoniecz** [kosmtik/kosmtik#150]
`node index.js export --help`:

```
Usage: node index.js export [project] [options]

project     Project to export.

Options:
   --mapnik-version             Optional mapnik reference version to be passed to Carto  [3.0.0]
   --proxy                      Optional proxy to use when doing http requests
   --keep-cache                 Do not flush cached metatiles on project load
   --renderer                   Specify a renderer by its name, carto is the default.  [carto]
   --localconfig                Path to local config file [Default: {projectpath}/localconfig.json|.js]
   --output PATH                Filepath to save in
   --width INT                  Width of the export  [1000]
   --height INT                 Height of the export  [1000]
   --bbox minX,minY,maxX,maxY   BBox to use [Default: project extent]
   --scale INT                  Scale the exported image  [1]
   --format FORMAT              Format of the export  [xml]
```

At this point I am guessing that "scale" is equivalent of zoom level (`--static_zoom=` in tilemill export).

**Comment by matkoniecz** [comment]
> At this point I am guessing that "scale" is equivalent of zoom level (--static_zoom= in tilemill export).

This guess unfortunately seems to be wrong.

**Comment by matkoniecz** [comment]
And what worse I see nowhere in https://github.com/kosmtik/kosmtik/blob/008db9517bea57e160f0838b0c25898dbc43ca1a/src/plugins/base-exporters/PNG.js place for zoom level to be set, hopefully I am missing something.

**Comment by nebulon42** [comment]
As far as I understand there is no zoom level to be set. The "zoom level" is determined by the bounding box (see https://github.com/kosmtik/kosmtik/blob/master/src/plugins/base-exporters/PNG.js#L26). I think that there is an error in the command line help, the parameter `--bbox` should be named `--bounds`.

For your use case you would have to provide a sufficient bounding box that in relation to your image size produces the zoom level you want. I will expand on this in your referenced issue.

**Comment by math1985** [comment]
I'm not sure about the command line interface, but the GUI has an Export button with a zoom level selector.

**Comment by nebulon42** [comment]
Yes, but if you set a zoom level different of the current one the image dimensions are modified to accommodate for the different bounding box on that zoom level. I'm not sure this is what @matkoniecz wants.

**Comment by matkoniecz** [comment]
> I think that there is an error in the command line help, the parameter --bbox should be named --bounds

Yes, it is a bug. I made a PR #151

**Comment by matkoniecz** [comment]
What `--scale` parameter is doing? I may make PR for it, but at this moment I am not sure what it is doing if not setting z level.

**Comment by matkoniecz** [comment]
OK, it now is clear that zoom level is set be settin bbox.

**Comment by yohanboniface** [comment]
`zoom` does not make sense for Mapnik, and it's more a web concept, thus why it's only available from the web exporter.
What we call "zoom" is at the end expressed by a bounding box and a size.
But I understand that cartographers may want to control which rendering will be used in the exported image, and for that want to force a certain zoom level without the need to compute by hand the bbox and/or the size.
We certainly should be able to add a `zoom` parameter to be used as `scale_denominator` from https://github.com/mapbox/carto/blob/af92b76f94b10887c23479a14f39bb688e1b06d5/lib/carto/tree/zoom.js#L66
