### ISSUE TITLE
Can't get kosmtik to zoom in beyond level 18

### ISSUE THREAD

**Issue by jr-dimedis** [kosmtik/kosmtik#157]
Hi,

I do some indoor mapping an need higher zoom levels.
Unfortunately I can't get kosmtik to go beyond level 18.

I tried setting the "maxzoom" property in my .mml file
but that didn't help. As well "minzoom" is ignored here,
so probably I am just at the wrong place to configure
this option, but I couldn't find any hints how to do it
correctly.

My .mml looks like this:

```json
{
    "Layer": [ ... ],
    "Stylesheet": [ ... ],

    "bounds": [
        -180,
        -85.0511,
        180,
        85.0511
    ],

    "center": [ 6.74149308972, 51.2602264368, 15 ],

    "maxzoom": 21,
    "minzoom": 15,

    "name": "indoor maps",
    "description": "indoor maps",
    "format": "png",
    "interactivity": false,

    "srs": "+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over",
    "background-color": "transparent",

    "attribution": "Data \u00a9 OpenStreetMap (and) contributors, ODbL"
}
```

Thanks!

Jörn

**Comment by jr-dimedis** [comment]
Yes, with "can't get beyond level 18"  I meant that clicking on (+) has no effect in zoom level 18. The button is greyed out.

My style is super simple and has no zoom restrictions, the Layer definitiions don't have any zoom params either. I just tried to add `properties: { "maxzoom": 22 }` but without luck.

I don't have a PostGIS database here at hand, just working on my generated .shp
files, so I currently can't test with a another style.

Thanks!

**Comment by kocio-pl** [comment]
I also have no problem with zooming in with [osm-carto](https://github.com/gravitystorm/openstreetmap-carto). Could you try it to compare?

**Comment by nebulon42** [comment]
Closing as more information is needed.
