### ISSUE TITLE
Compare against 'frozen' version

### ISSUE THREAD

**Issue by systemed** [kosmtik/kosmtik#158]
Often, when working on a map style, I'll keep playing around with a colour and/or icon until I get it right. With that in mind, it's good to be able to visually compare against the previous version. 

At present I take a screenshot of the pre-change version. It would be nice to be able to 'freeze' the current stylesheet in one pane, while continuing to develop in another pane.

Could possibly be implemented as part of the map-compare plugin.

**Comment by yohanboniface** [comment]
Related #100 

(Hi from Nivernais Canal :) )

**Comment by systemed** [comment]
Very jealous... everyone over here always says the Nivernais is the prettiest French canal!

**Comment by yohanboniface** [comment]
> Very jealous... everyone over here always says the Nivernais is the prettiest French canal!

Hey, what about a river OSM sprint while boating in the Nivernais then? :)

**Comment by yohanboniface** [comment]
Closing here to continue on #100.
