### ISSUE TITLE
Duplicated tiles with xray mode when above max zoom of VT source

### ISSUE THREAD

**Issue by pnorman** [kosmtik/kosmtik#162]
![image](https://cloud.githubusercontent.com/assets/1190866/17874202/ec9db17c-687e-11e6-81b6-a001d003d82c.png)

This is on z19 and the tile shown is from z16, the max zoom of the vector tile source. The style is a .tm2 project and the source is a .tm2source

**Comment by JesseCrocker** [comment]
Duplicate of #146
