### ISSUE TITLE
Disable crosshairs by default?

### ISSUE THREAD

**Issue by kocio-pl** [kosmtik/kosmtik#173]
How could I get rid of crosshair? I'm not sure if it's good to have it on by default, and at least I'd like to store this setting in configuration.

**Comment by gravitystorm** [comment]
`Settings > show crosshairs` is a GUI way to switch them off, but I don't know if there's a setting for it.

**Comment by nebulon42** [comment]
You can also put `showCrosshairs: false` in your `HOMEDIR/.config/kosmtik.yml`, which will disable it automatically.

**Comment by pnorman** [comment]
> I'm not sure if it's good to have it on by default

I'm in agreement with this. Like showing MT bounds, it's useful for some specialised cases, but not a general purpose feature

**Comment by nebulon42** [comment]
I have rephrased the title and reopened. I'm not usually bothered by the crosshair, but also do not need it much in general. When doing screenshots I tend to disable them.

**Comment by yohanboniface** [comment]
Agreed on disabling by default, as far as we have the setting to enable it by default for people who want it. :)

(Sorry for my lag, I'm actually in a mission in Jordan for two weeks…)
