### ISSUE TITLE
Review policy

### ISSUE THREAD

**Issue by nebulon42** [kosmtik/kosmtik#178]
The Kosmtik organisation has now a few members with push access. How should changes be handled? I have so far directly committed two small changes and opened PRs for everything else.

Shall there be PRs that have to be reviewed by somebody else for all changes (even the smallest ones)? E.g. openstreetmap-carto has such a policy. Is this feasible here?

Or should everybody decide at their discretion what should be reviewed and what not?

**Comment by yohanboniface** [comment]
I think PRs is the way to go.
I'll conform to this too from now on.

Let's see if it works like this. And in case we don't have the collective bandwidth for that, we'll discuss again to adapt the workflow.

**Comment by nebulon42** [comment]
Great, closing this for now. We should re-open if we have more to discuss.
