### ISSUE TITLE
error while installation

### ISSUE THREAD

**Issue by bung87** [kosmtik/kosmtik#183]
npm WARN lifecycle mapnik@3.5.14~preinstall: cannot run in wd %s %s (wd=%s) mapnik@3.5.14 npm install node-pre-gyp /usr/local/lib/node_modules/.staging/mapnik-b95e22e5

> mapnik@3.5.14 install /usr/local/lib/node_modules/kosmtik/node_modules/mapnik
> node-pre-gyp install --fallback-to-build

node :5.10.1
osx:10.11.5 (15F34)

**Comment by yohanboniface** [comment]
Seems to be node-mapnik related, you should open an issue [there](https://github.com/mapnik/node-mapnik) instead.
