### ISSUE TITLE
Tile not updated when project changes

### ISSUE THREAD

**Issue by cquest** [kosmtik/kosmtik#191]
The metatiles in /tmp/ are not updated when the project files are updated.

**Comment by nebulon42** [comment]
I think I have experienced this too occasionally.

**Comment by math1985** [comment]
I can confirm this too. My relevant log files:

[Core] Creating metatiles cache dir tmp/osm/meta
[Core] Deleting previous metatiles tmp/osm/meta
[Core] Created vector cache dir tmp/osm/vector

**Comment by nebulon42** [comment]
For those not aware of it, there is a setting to keep or flush the metatile cache on project start: https://github.com/kosmtik/kosmtik/blob/145ba51458b6776dfab11b46209aa75add74e229/src/Config.js#L139

**Comment by math1985** [comment]
`--keep-cache=false` does not solve the problem for me.

**Comment by nebulon42** [comment]
Yes, I bet it doesn't. It just cleans the cache on startup. Failed invalidation on changes is not covered by this, so this was not meant as a workaround. Sorry if it sounded like that.

**Comment by math1985** [comment]
It seems this behaviour was introduced in https://github.com/kosmtik/kosmtik/commit/4e97d2bed4c0f601320c0b47d4103527b51806b0 .

**Comment by nebulon42** [comment]
@math1985 Thanks for investigating.
@math1985, @cquest Please check if this is solved for you with latest master.

**Comment by math1985** [comment]
Thanks, confirmed fixed!
