### ISSUE TITLE
Broken close icon

### ISSUE THREAD

**Issue by pnorman** [kosmtik/kosmtik#20]
![image](https://cloud.githubusercontent.com/assets/1190866/5169878/e7f8e2be-73bf-11e4-8bbe-c63462449d8f.png)

Probably the same issue as #10

**Comment by yohanboniface** [comment]
Still broken?

**Comment by pnorman** [comment]
still broken

**Comment by pnorman** [comment]
I'm not sure how to get the view you have, here's what I see

![image](https://cloud.githubusercontent.com/assets/1190866/6433686/6e7860f6-c02a-11e4-8b56-c6df004c89a1.png)

**Comment by yohanboniface** [comment]
Thanks, should be fixed now, please check :)
