### ISSUE TITLE
text-face-name expecting type font, getting string.

### ISSUE THREAD

**Issue by nathancahill** [kosmtik/kosmtik#209]
Mapnik: 3.0.12.
Kosmtik: 0.0.13

With a style that includes this:

```
text-face-name: 'DejaVu Sans Book';
```

I get this error:
```
Invalid value for text-face-name, the type font is expected. DejaVu Sans Book (of type string)  was given.
```
Tried with multiple font names, same error. Note, this style works fine in TileMill.

**Comment by nebulon42** [comment]
Probably duplicate of #101 or #156. Upstream carto issue: https://github.com/mapbox/carto/issues/242
Do the fonts you want to reference actually exist on your system? Are you on macOS?

**Comment by nathancahill** [comment]
Looks like that upstream issue is the problem. Odd that it works with TileMill though. I do have the fonts installed.

**Comment by nebulon42** [comment]
The upstream issue is only about fonts that are not installed. If the fonts are on your system and are not found this is another problem.

**Comment by nathancahill** [comment]
I'll see if I can replicate again. I switch to using `Map { font-directory }` which I couldn't get to work either, and ultimately ended up running on a Docker image with fonts installed (which worked right away).
