### ISSUE TITLE
Carto not found when installing

### ISSUE THREAD

**Issue by pnorman** [kosmtik/kosmtik#215]
```
pnorman@pippin:~/osm/kosmtik$ npm install
npm ERR! 404 Not Found
npm ERR! 404
npm ERR! 404 'mapbox/carto' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'kosmtik'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 4.7.0-1-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/pnorman/osm/kosmtik
npm ERR! node -v v4.6.1
npm ERR! npm -v 1.4.21
npm ERR! code E404
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pnorman/osm/kosmtik/npm-debug.log
npm ERR! not ok code 0
```

I've worked around it by replacing `"@mapbox/carto"` with `"carto"` in package.json, and `sed -i 's_@mapbox/carto_carto_g' src/back/renderer/Carto.js` but this isn't the right fix.

**Comment by nebulon42** [comment]
I'm not sure what you are hitting here. I just cloned a fresh copy and tried to install it. It worked without error. I have also checked that there are no incorrect `mapbox/carto` (instead of `@mapbox/carto`) refs in the code.

**Comment by pnorman** [comment]
I've added the rest of the message. I can add npm-debug.log if needed

**Comment by MaelREBOUX** [comment]
Hello @pnorman 

Read my story for a correct install : https://github.com/kosmtik/kosmtik/issues/212#issuecomment-271412613
;)

I did not have any problem with npm install -g @mapbox/carto

**Comment by pnorman** [comment]
> Read my story for a correct install : #212 (comment)
> ;)
> 
> I did not have any problem with npm install -g @mapbox/carto

I'm not doing a global install.

**Comment by yohanboniface** [comment]
> npm -v 1.4.21

I wonder if scoped packages are not npm > 1.5.0 only

**Comment by nebulon42** [comment]
Nice find, correct.
see e.g. https://github.com/npm/npm/issues/5239#issuecomment-49395422

**Comment by nebulon42** [comment]
I have now specified a required npm version for carto: https://github.com/mapbox/carto/commit/fc18caa4e9e55e1bd00b6dc87a355cc9ee38f6fe

Guess we should do the same here.

**Comment by nebulon42** [comment]
I'm closing this as we can't influence the carto scoped package change and per discussion in #218. Strictly speaking I could change it, but I have to respect Mapbox's decision.
