### ISSUE TITLE
0.0.14/0.0.15

### ISSUE THREAD

**Issue by nebulon42** [kosmtik/kosmtik#228]
@yohanboniface I think you forgot to push the 0.0.14 tag/commit you created. I need to change carto from `@mapbox/carto` back to `carto`. I would then release 0.0.15. For this I need an up-to-date package.json. The current one still shows the version as 0.0.13.

Seeking permission to do this without PR. :)

**Comment by yohanboniface** [comment]
Ooops, sorry!
Done!
