### ISSUE TITLE
Install fails with node 6.9.5

### ISSUE THREAD

**Issue by hevilp** [kosmtik/kosmtik#229]
`/srv/umap
└── kosmtik@0.0.15

npm WARN enoent ENOENT: no such file or directory, open '/srv/umap/package.json'
npm WARN umap No description
npm WARN umap No repository field.
npm WARN umap No README data
npm WARN umap No license field.
`

**Comment by nebulon42** [comment]
Hm, looks a bit odd. What else is in this directory? npm seems to complain about the contents of the `umap` directory somehow. It looks to me like kosmtik was installed. What command did you issue? Is there a `node_modules/kosmtik` directory?

**Comment by hevilp** [comment]
here on windows:


[2017-02-21T19_10_35_654Z-debug.log.txt](https://github.com/kosmtik/kosmtik/files/791240/2017-02-21T19_10_35_654Z-debug.log.txt)

**Comment by nebulon42** [comment]
`54159 error mapnik@3.5.14 preinstall: `npm install node-pre-gyp` indicates that this is a problem with the Mapnik library.

https://github.com/mapnik/node-mapnik#depends suggests that it does not work on Windows with Node v6 or it hasn't been tested. Maybe using Node v4 or v5 for Kosmtik would help?

As it is a problem with a dependency we cannot do much about that on our side.
