### ISSUE TITLE
Building fails

### ISSUE THREAD

**Issue by andischan** [kosmtik/kosmtik#230]
https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.5.14/Release/node-v51-linux-x64.tar.gz is non-existant, which leads to a bunch of errors:

Full log: https://paste.ee/p/M72X5

**Comment by pnorman** [comment]
Looks like a [node-mapnik](https://github.com/mapnik/node-mapnik) error

**Comment by nebulon42** [comment]
Yes, and your node v7 might be the problem. https://github.com/mapnik/node-mapnik#depends does not list v7, so it is either not tested or not working or both. I suggest to try node v6.

@springmeyer we are getting quite some user reports about not working node v7 installs. Is node v7 supported with node-mapnik?
