### ISSUE TITLE
Pool draining

### ISSUE THREAD

**Issue by pnorman** [kosmtik/kosmtik#24]
```
/home/pnorman/kosmtik/node_modules/generic-pool/lib/generic-pool.js:316
      throw new Error("pool is draining and cannot accept work");
            ^
Error: pool is draining and cannot accept work
    at Object.me.acquire (/home/pnorman/kosmtik/node_modules/generic-pool/lib/generic-pool.js:316:13)
    at ProjectServer.tile (/home/pnorman/kosmtik/src/back/ProjectServer.js:50:18)
    at ProjectServer.serveTile (/home/pnorman/kosmtik/src/back/ProjectServer.js:45:15)
    at tile (/home/pnorman/kosmtik/src/back/ProjectServer.js:35:108)
    at StateBase.when (/home/pnorman/kosmtik/src/back/StateBase.js:51:33)
    at ProjectServer.serve (/home/pnorman/kosmtik/src/back/ProjectServer.js:35:70)
    at PreviewServer.forwardToProject (/home/pnorman/kosmtik/src/back/PreviewServer.js:73:23)
    at PreviewServer.serve (/home/pnorman/kosmtik/src/back/PreviewServer.js:67:42)
    at Server.EventEmitter.emit (events.js:98:17)
    at HTTPParser.parser.onIncoming (http.js:2108:12)
pnorman@pnorman-desktop:~/kosmtik$
```

I don't know exactly when this happened, but probably when saving a file and triggering a reload.

**Comment by pnorman** [comment]
when doing a `git checkout` I get multiple loading messages

```
[Core] Loading project from /home/pnorman/osm/openstreetmap-carto/repo/project.yaml
[Core] Loading project from /home/pnorman/osm/openstreetmap-carto/repo/project.yaml
[Core] Loading project from /home/pnorman/osm/openstreetmap-carto/repo/project.yaml
[Core] Loading project from /home/pnorman/osm/openstreetmap-carto/repo/project.yaml
[Core] Loading project from /home/pnorman/osm/openstreetmap-carto/repo/project.yaml
[Core] Loading project from /home/pnorman/osm/openstreetmap-carto/repo/project.yaml
[Core] Generating Mapnik XML…
[Core] Using mapnik version 2.2.0
[Core] Loading map…
[Core] Map ready
[Core] Loading map…
[Core] Map ready
[httpserver] /repo/reload/ 200
[Core] Loading map…
[Core] Map ready
[Core] Loading map…
[Core] Map ready
[httpserver] /repo/reload/ 200
[Core] Loading map…
[Core] Map ready
[Core] Loading map…
[Core] Map ready
[httpserver] /repo/reload/ 200
[Core] Loading map…
[Core] Map ready
[Core] Loading map…
[Core] Map ready
[httpserver] /repo/reload/ 200
[Core] Loading map…
[Core] Map ready
[Core] Loading map…
[Core] Map ready
[httpserver] /repo/reload/ 200
[Core] Loading map…
[Core] Map ready
[Core] Loading map…
[Core] Map ready
[httpserver] /repo/reload/ 200
```

It didn't get a pool draining error, but the multiple events are not SFTP specific.

This was on FreeBSD with ZFS, while the earlier reports were on Ubuntu w/ ext4, so it's not OS specific.

I did get a pool draining error saving with samba, but didn't save it.

**Comment by yohanboniface** [comment]
About the "Pool draining error", I just got it, and here are the steps to reproduce:
- load a valid map
- add an error in a mss file
- force reload the web page (not the map)

I'm moving to work now, but will have a look on it tonight; now that I can reproduce, it should be easy to fix. :)

@pnorman about the multiple loads, do you had it also on Ubuntu, or on Ubuntu you only had the "pool draining error"?

**Comment by pnorman** [comment]
> @pnorman about the multiple loads, do you had it also on Ubuntu, or on Ubuntu you only had the "pool draining error"?

both errors on both OSes

**Comment by yohanboniface** [comment]
Out of curiosity, how are you refreshing your map? Hitting `Ctrl+R` or `Ctrl+Shift+R` or something else?

In case it's not clear, the first reload the page, as per browser request, while the second (`Ctrl-Shift-R`) only ask the application to reload the map.

The pool draining issue appears, at least as I'm able to reproduce it, when there is an issue in the code and we reload the page it self, not the map. This issue needs to be fixed anyway (but it's not that easy given that the Mapnik XML is invalid at this point). Plus it's possible that you hit this with another scenario.

**Comment by pnorman** [comment]
I will have done both

**Comment by yohanboniface** [comment]
@pnorman this last commit may fix the initial "pool draining" issue (at least it fixes the one I was able to reproduce).

About the multiple loads, are you able to describe steps to reproduce?

**Comment by pnorman** [comment]
> @pnorman this last commit may fix the initial "pool draining" issue (at least it fixes the one I was able to reproduce).

Yes, looks to be fixed.

> About the multiple loads, are you able to describe steps to reproduce?

Open a project with Kosmtik. In another terminal window, do `git checkout <some other branch>`

Result is

```
[httpserver] /repo/poll/ 200
[Core] Loading project from /home/pnorman/osm/openstreetmap-carto/repo/project.yaml
[Core] Loading project from /home/pnorman/osm/openstreetmap-carto/repo/project.yaml
[Core] Loading project from /home/pnorman/osm/openstreetmap-carto/repo/project.yaml
[Core] Loading project from /home/pnorman/osm/openstreetmap-carto/repo/project.yaml
[Core] Loading project from /home/pnorman/osm/openstreetmap-carto/repo/project.yaml
[Core] Generating Mapnik XML…
[Core] Using mapnik version 2.2.0
[Core] Loading map…
[Core] Map ready
[Core] Loading map…
[Core] Map ready
[httpserver] /repo/reload/ 200
[Core] Loading map…
[Core] Map ready
[Core] Loading map…
[Core] Map ready
[httpserver] /repo/reload/ 200
[Core] Loading map…
...
```

**Comment by pnorman** [comment]
Haven't hit a pool draining since the commit, so closing
