### ISSUE TITLE
Add "current view" button in export panel

### ISSUE THREAD

**Issue by yohanboniface** [kosmtik/kosmtik#25]
To use current view as bbox for export.

**Comment by kocio-pl** [comment]
I miss this button a lot. It looks like the export box is set on the starting view and in case if you float a lot from there, the easiest way is to reopen the browser view with new position.

**Comment by yohanboniface** [comment]
Done!
Please update kosmtik, test, and give feedback :)

**Comment by kocio-pl** [comment]
Great! I tested it and it works as expected - and that was a blazing fast reaction, thanks! :smiley:
