### ISSUE TITLE
Using CSVs as datasource

### ISSUE THREAD

**Issue by hope15** [kosmtik/kosmtik#250]
Hello, 
I would like to ask if it's still possible to use CSVs as data source when using your project and if yes, what type I must specify to use data with latitude/longitude fields.

Thanks in advance!
Marcel

**Comment by nebulon42** [comment]
Datasources are not specified by Kosmtik but are a feature of Mapnik. It seems that the support for CSV is unknown or not there (https://github.com/mapnik/mapnik/wiki/PluginArchitecture). Kosmtik uses [node-mapnik](https://github.com/mapnik/node-mapnik) for rendering so you would have to ask there if it supports CSV. If it does then also Kosmtik does.
