### ISSUE TITLE
Testing current Mapnik

### ISSUE THREAD

**Issue by kocio-pl** [kosmtik/kosmtik#271]
How could I easily test current Mapnik code (from git repository) with Kosmtik - probably not messing with my existing system?

**Comment by yohanboniface** [comment]
I guess something like `npm install mapnik/node-mapnik --build-from-source`, @springmeyer?

**Comment by springmeyer** [comment]
Yes, you'd need `mapnik-config` on your path. Then you'd want to clone node-mapnik and build 
locally from source. See https://github.com/mapnik/node-mapnik#source-build. Then once build you can link that version of node-mapnik into kosmtik like:

```
cd kosmtik
npm link ../node-mapnik
```

**Comment by kocio-pl** [comment]
Linking tries to install something outside the kosmtik directory (`/usr/local/lib/node_modules`). Is this really necessary? I would prefer clean solution, with changing things just in local directory, just like regular Kosmtik.

**Comment by springmeyer** [comment]
That is the way that `npm link` works. I share your astonishment - you would hope it would work with relative paths, but it does not. The alternative way to point at a source-compiled node-mapnik in another directory is to make sure the one that might have been installed inside the `node_modules` tree is removed. And then point to another one that you've build from source. So if `kosmtik` is at `/home/kosmtik` and you've built node-mapnik from source at `/home/node-mapnik` you can allow `kosmtik` to find node-mapnik by doing:

```
export NODE_PATH=/home/node-mapnik/lib
```

In fact, once that is working you could do this from anywhere on your system:

```
node -e "require('mapnik')"
```

**Comment by springmeyer** [comment]
I think that is happening because mapnik-reference needs an update. I've ticketed this at https://github.com/mapnik/mapnik-reference/issues/143

**Comment by kocio-pl** [comment]
We have Mapnik 3.0.16 now:

https://github.com/mapnik/mapnik/blob/v3.0.16/CHANGELOG.md#3016

Is it possible to compile node-mapnik with this version?

**Comment by springmeyer** [comment]
@kocio-pl it should, if you try to source compile use the `v3.0.x` branch of node-mapnik. If you hit problems please ticket at https://github.com/mapnik/node-mapnik/issues and /cc @artemp

**Comment by kocio-pl** [comment]
I was able to test 3.0.16 with Kosmtik on Ubuntu this way:
- building experimental Mapnik packages from Debian and installing it in my system
- compiling node-mapnik branch v3.0.x using system Mapnik version (probably using Clang instead of GCC, IIRC)
- replacing kosmtik/node_modules/mapnik with a symboli link to node-mapnik directory

It would be better if we have some simpler way of testing different Mapnik versions (especially from current git master repo), but that's enough for me now. Thank you for all the help!

**Comment by kocio-pl** [comment]
I'm still not able to compile and use the current Mapnik from repo in Kosmtik, but here is more detailed procedure for using it with Debian Mapnik 3.0.x packages:

https://github.com/gravitystorm/openstreetmap-carto/issues/1391#issuecomment-371167642
