### ISSUE TITLE
Update to next mapnik version

### ISSUE THREAD

**Issue by sommerluk** [kosmtik/kosmtik#295]
[Mapnik 3.0.22](https://github.com/mapnik/mapnik/releases/tag/v3.0.22) has been released. Also mapnik-reference has been [updated](https://github.com/mapnik/mapnik-reference/pull/153) to 3.0.22. Furthermore a [corresponding new npm package](https://www.npmjs.com/package/mapnik-reference/v/8.10.0) has been published with version number 8.10.0. Also CartoCSS had a [new release 1.2.0](https://github.com/mapbox/carto/releases/tag/v1.2.0) which updates its dependencies to Mapnik 3.0.22 respectively mapnik-reference 8.10.0. This CartoCSS release is also available as npm package [carto 1.2.0](https://www.npmjs.com/package/carto/v/1.2.0).

It would be great to have a Kosmtik version that is using these new software package versions.

**Comment by sommerluk** [comment]
It seems that simply raising the carto version breaks kosmtik. I've played around with the source, raising the carto version numer in package.json. And carto 0.18.2 is still working, while carto 1.0.1 not. The error message is “Project not loaded properly.”. Any ideas?

**Comment by sommerluk** [comment]
I'm asking because I would like to develop a feature for openstreetmap-carto, and this feature relies on Mapnik 3.0.22…

**Comment by kocio-pl** [comment]
Hi, @yohanboniface, is there anything you need some help with to solve this issue?

**Comment by kocio-pl** [comment]
@nebulon42 Since this repo is not updated from August 2018 and there is no response from project leader, maybe you could help us?

**Comment by yohanboniface** [comment]
> is there anything you need some help with to solve this issue?

Create a Pull Request that updates the dependencies where tests passe ;)

**Comment by yohanboniface** [comment]
(I plan to have a look myself, but with respect to my schedule, thus if someone is more in a hurry => working PR ;) )

**Comment by yohanboniface** [comment]
> It seems that simply raising the carto version breaks kosmtik. I've played around with the source, raising the carto version numer in package.json. And carto 0.18.2 is still working, while carto 1.0.1 not. The error message is “Project not loaded properly.”. Any ideas?

Which Node version? I've just upgraded to latest Carto on my machine, and it works (running Node LTS v8.11.2)

(Each time I need to play with Node and NPM I regret that kosmtik is running this ecosystem, damn)

**Comment by yohanboniface** [comment]
Latests Mapnik also works for me, with LTS Node

**Comment by kocio-pl** [comment]
Thanks! We have some problems to solve in the meantime (https://github.com/gravitystorm/openstreetmap-carto/issues/3717), but when we're done, we will need new Kosmtik release for a Docker container to have a well defined environment. Could you make such release?

**Comment by yohanboniface** [comment]
> Could you make such release?

yep

**Comment by nebulon42** [comment]
Just for future reference: I have no commit rights to this repository anymore.

**Comment by sommerluk** [comment]
Well, I had branched from latest kosmtik release, not from master… `node -v` 8.15.0 and `npm -v` 6.4.1 (and even `npm8 -v` gives 6.4.1, no idea why).

The master branch did not work for me. This was the reason I did not branch from master.

Now, after you have updated carto and so on, at `bd6b7e5` cloning and doing `npm install`, still does not work: After refreshing the image in the browser, this happens on the command line:

```
Trace
    at ProjectServer.raise (/home/sommerluk/Dokumente/OSM/kosmtik/src/back/ProjectServer.js:267:13)
    at /home/sommerluk/Dokumente/OSM/kosmtik/src/back/ProjectServer.js:85:34
    at /home/sommerluk/Dokumente/OSM/kosmtik/src/back/MetatileBasedTile.js:47:45
    at FSReqWrap.oncomplete (fs.js:135:15)
std::bad_alloc
[httpserver] /openstreetmap-carto-with-data/tile/4/7/7.png?t=1552594486370 500
[httpserver] /openstreetmap-carto-with-data/poll/ 200
Trace
    at ProjectServer.raise (/home/sommerluk/Dokumente/OSM/kosmtik/src/back/ProjectServer.js:267:13)
    at /home/sommerluk/Dokumente/OSM/kosmtik/src/back/ProjectServer.js:85:34
    at /home/sommerluk/Dokumente/OSM/kosmtik/src/back/MetatileBasedTile.js:47:45
    at FSReqWrap.oncomplete (fs.js:135:15)
std::bad_alloc
[httpserver] /openstreetmap-carto-with-data/tile/4/7/6.png?t=1552594486370 500
./kosmtik-run.sh: Zeile 2:  4214 Getötet                node /home/sommerluk/Dokumente/OSM/kosmtik/index.js serve /home/sommerluk/Dokumente/OSM/openstreetmap-carto-with-data/project.mml

```

**Comment by kocio-pl** [comment]
For me it works without such problems with master branch (I'm not talking about style in itself - https://github.com/gravitystorm/openstreetmap-carto/issues/3717). Using Ubuntu 18.04.2:

$ node -v
v8.10.0

$ npm -v
3.5.2

**Comment by yohanboniface** [comment]
> doing npm install

did you `rm -rf node_modules` before? 

Node is… playful ;)

**Comment by sommerluk** [comment]
> did you `rm -rf node_modules` before?

I have a local clone of https://github.com/kosmtik/kosmtik.git with master at bd6b7e5. I do `git checkout XXXXXXX` to chose a specific commit. Than I create a copy of the hole `kosmtik` repository folder and run `npm install` within this copy. So I suppose this is a clean installation.

These steps works still fine for bdbef4d, but are broken since the following 49f6483 which bumps the mapnik npm package to 4.x.

(Question: If not bumping to recent Mapnik: Would Carto 1.2.0 still work when using Mapnik 3.0.22 features?)

**Comment by sommerluk** [comment]
I'm using openSUSE 15.0 with  Geo software from the Application:Geo repository. As they provide only mapnik-3.0.20, I provide a [mapnik-3.0.22 package in my home repository](https://build.opensuse.org/package/show/home:sommerluk:branches:Application:Geo/mapnik) which I use currently.

**Comment by sommerluk** [comment]
If I take current master 49f6483 and change in `package.json` the mapnik dependency back to 3.7.2 than it renders (at least code that does not depend on 3.0.22). I will test code that uses 3.0.22 features…

**Comment by sommerluk** [comment]
For Mapnik 3.0.22 features, when using the npm package mapnik 3.7.2 than these features are ignored while rendering.

**Comment by sommerluk** [comment]
Cross-reference node-mapnik issue: https://github.com/mapnik/node-mapnik/issues/914

**Comment by sommerluk** [comment]
I guess this is more a node-mapnik problem, and as kosmtik has updated to Carto 1.2.0 in master, this issue can be close once a release has been made?

**Comment by kocio-pl** [comment]
@yohanboniface Hi, is it possible to make a new Kosmtik release or were there some issues with it?

**Comment by sommerluk** [comment]
Solved in current master. Release requested in #309 so closing this one as solved.

Thanks for the work!
