### ISSUE TITLE
kosmtik fetch-remote does not support HTTPS

### ISSUE THREAD

**Issue by Phyks** [kosmtik/kosmtik#306]
Hi,

It seems Kosmtik fetch-remote plugin does not support HTTPS links. This is probably due to this faulty `indexOf` value [here](https://github.com/kosmtik/kosmtik-fetch-remote/blob/master/index.js#L77).

Best,

**Comment by yohanboniface** [comment]
Should be fixed with https://github.com/kosmtik/kosmtik-fetch-remote/commit/7d7654bf6cc7e1590cb69d9db0e84931c4976e8e
