### ISSUE TITLE
404 error for simplified-land-polygons-complete-3857.zip

### ISSUE THREAD

**Issue by jragusa** [kosmtik/kosmtik#308]
On a fresh install I get a 404 error for `simplified-land-polygons-complete-3857.zip` (only 288 bytes):

```bash
kosmtik_1  | 2-1. Downloading 'simplified-land-polygons-complete-3857'...
kosmtik_1  |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
kosmtik_1  |                                  Dload  Upload   Total   Spent    Left  Speed
100   288  100   288    0     0   1645      0 --:--:-- --:--:-- --:--:--  1636
kosmtik_1  | 
kosmtik_1  | 
kosmtik_1  |    Error: download failed. (error code: 404, error reason: Not Found)
```
I get the same message with `scripts/get-shapefiles.py -s`

As a result I don't have any map displayed and I get this message at the bottom: 

> Shape Plugin: shapefile '/openstreetmap-carto/data/simplified-land-polygons-complete-3857/simplified_land_polygons.shp' does not exist encountered during parsing of layer 'world' in Layer

**Comment by pnorman** [comment]
These look like errors in your stylesheet, nothing to do to with Kosmtik. Before reporting a problem with the style you're using, double-check you have the latest version

**Comment by jragusa** [comment]
Ok, closing since problem is resolved
