### ISSUE TITLE
Issue with Postgis Plugin when running openstreetmap-carto

### ISSUE THREAD

**Issue by tajchert** [kosmtik/kosmtik#331]
I server openstreetmap-carto (5.3.1 without any changes) with Kostik with Node 9.11.2 on MacOS and I get no preview but the error of Postgis Plugin:

```
[httpserver] /openstreetmap-carto/tile/4/10/6.png?t=1617640722569 500
Trace
    at ProjectServer.raise (/usr/local/lib/node_modules/kosmtik/src/back/ProjectServer.js:261:13)
    at /usr/local/lib/node_modules/kosmtik/src/back/ProjectServer.js:75:30
    at /usr/local/lib/node_modules/kosmtik/node_modules/generic-pool/lib/generic-pool.js:283:11
    at loaded (/usr/local/lib/node_modules/kosmtik/node_modules/mapnik-pool/index.js:23:37)
Postgis Plugin: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
Connection string: ' dbname=gis connect_timeout=4'
  encountered during parsing of layer 'landcover-low-zoom' in Layer
```
I'm able to serve CartoDB positron style without any issues. Any idea what the issue might be?

**Comment by yohanboniface** [comment]
Not sure it's related to kostmik.
Can you connect with `psql gis` ?

**Comment by tajchert** [comment]
It turned out openstreetmap-cart requires running Kosmtik as a Docker as it has some custom configuration - https://github.com/gravitystorm/openstreetmap-carto/blob/master/DOCKER.md
I missed this and not set up Kosmtik properly, running it from Docker works well.
