### ISSUE TITLE
Cannot call method 'indexOf' of null

### ISSUE THREAD

**Issue by pnorman** [kosmtik/kosmtik#36]
I switched windows back to see this
```
[httpserver] /repo/poll/ 200

/usr/home/pnorman/osm/kosmtik/src/back/ProjectServer.js:18
            if (filename.indexOf('.') === 0) return;
                         ^
TypeError: Cannot call method 'indexOf' of null
    at FSWatcher.<anonymous> (/usr/home/pnorman/osm/kosmtik/src/back/ProjectServer.js:18:26)
    at FSWatcher.emit (events.js:98:17)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1051:12)
```

**Comment by yohanboniface** [comment]
Humm, that may be an edge case when computing the project root.

Can you give me the exact command line you used to run kosmtik?

**Comment by pnorman** [comment]
`node index.js serve --host 0.0.0.0 ~/osm/openstreetmap-carto/repo/project.yaml`
revision 1e08fd2b4627f870d3ae723711bf6ae1a48ae506

**Comment by yohanboniface** [comment]
Which platform? I wonder if it can be one of the caveats of [fs.watch](http://nodejs.org/api/fs.html#fs_filename_argument).

**Comment by pnorman** [comment]
FreeBSD 10.1

**Comment by yohanboniface** [comment]
OK, that may explain. I've pushed a check, to do some more checks and log only if filename has been provided. Can you try it?

**Comment by yohanboniface** [comment]
As per IRC discussion, seems fixed. Of course, reopen if it's finally not the case.
