### ISSUE TITLE
Wrong overwrite when installing kosmtik-map-compare

### ISSUE THREAD

**Issue by ThomasG77** [kosmtik/kosmtik#39]
When I do

```
node index.js plugins --install kosmtik-map-compare
```

I get below logs
```
[Core] Loading config from /root/kosmtik/projects/OSMBright/localconfig.json
[Core] Loading plugin from ../plugins/base-exporters/index.js
[Core] Loading plugin from ../plugins/hash/index.js
[Core] Loading plugin from ../plugins/local-config/index.js
[Core] Loading plugin from ../plugins/datasource-loader/index.js
npm WARN package.json kosmtik-overpass-layer@0.0.2 No repository field.
npm WARN package.json leaflet-formbuilder@0.0.6 No README data
kosmtik-map-compare@0.0.9 node_modules/kosmtik-map-compare
[Core] Successfully installed package kosmtik-map-compare
[Core] Attached plugin: kosmtik-map-compare
[Core] Saved env conf to /root/kosmtik/projects/OSMBright/localconfig.json
```

The issue is the fact that doing `cat projects/OSMBright/localconfig.json` returns a yml notation. Then, when restarting, it fails because the json was replaced with the yml content e.g

```
- where: center
  then:
    - 29.9377
    - -3.4216
    - 2
```

FIY, I've set `export KOSMTIK_CONFIGPATH=/root/kosmtik/projects/OSMBright/localconfig.json`

**Comment by yohanboniface** [comment]
I confess there is no clear documentation about that, but `KOSMTIK_CONFIPATH` is not for the project config, bug instead for kosmtik config itself.

About the localconfig.json, you don't need to add an env var, naming it like this is enough for it to be loaded.
