### ISSUE TITLE
Wrong tiles when rendering whereas the "Inspect" is correct

### ISSUE THREAD

**Issue by ThomasG77** [kosmtik/kosmtik#41]
To try the application, I've retrieved the osm-bright from @mapbox, loaded the local data using imposm but when I'm using the inspect tool, the rendering is OK whereas the "classic" rendering fails due to a behaviour related to tiles scheme.

See both images below to get an illustration

![osm_bright_inspected](https://cloud.githubusercontent.com/assets/642120/5892993/dc253564-a4d4-11e4-81e9-8fd0ef8aee86.png)
![osm_bright_rendered](https://cloud.githubusercontent.com/assets/642120/5892994/dffc01a4-a4d4-11e4-85ee-be339b2c1b91.png)

**Comment by yohanboniface** [comment]
Humm, that may be a side effect of the feature I'm working on.
What is the last commit your are running?

**Comment by ThomasG77** [comment]
To give more infos, my Mapnik is `2.3` on Ubuntu 14.04 and my Node version is `v0.10.35`
The installed code at the moment is using this commit https://github.com/kosmtik/kosmtik/commit/5c1b41280de2faa274750adf3834d1da1a891e25

**Comment by yohanboniface** [comment]
OK, thanks, so the vector tile based PNG export I'm working on is not guilty.

Can you try to load map in another browser, and load one of the "wrong" tiles in a separate window and make sure it's not from cache.

I need to find a way to reproduce.

**Comment by yohanboniface** [comment]
Just in case, can you try to load [this project](https://github.com/yohanboniface/thank-you-map)? It should be configless (using remote vector tiles).

**Comment by yohanboniface** [comment]
Also, what is the "metatile" value of your mml file?

**Comment by ThomasG77** [comment]
I just tried it and it works perfectly. The use case seems to be related to the osm-bright project.

**Comment by ThomasG77** [comment]
After cleaning my cache, it's working without the previous issue mentioned. Feel ashamed to make you lose time...
I should miss why this behaviour happened.
The worst is that the issue was in both browsers (FF and Chrome)

**Comment by yohanboniface** [comment]
OK, weird.

**Comment by woodpeck** [comment]
I can confirm that this error still occurs with the current kosmtik version (1533efde3bd2f5246eb04e7bc9c273314efbac7d) when you use the OsmBright style (I have a slightly modified style but I guess it should be fairly standard) and do not explicitly set a "metatile" parameter. Set a "metatile" of "1" or "2" and it works ok...

**Comment by woodpeck** [comment]
btw. if you accidentally write

    "metatile" : "2",

then everything breaks (in my case - only blue blackground instead of any meaningful rendering). Drop the quotation marks around the "2" and it's ok.

**Comment by yohanboniface** [comment]
@woodpeck Can you have another try after updating kosmtik (`git pull` is enough): I've casted the `metatile` value, plus added a default when it's missing.

**Comment by woodpeck** [comment]
Updatded to 24a97432a175f4ba6ba4d2886ea80615883e9bb2 and now it works without a metatile setting, and also works if you use quotes. That will certainly save some headache for future users - thank you for the quick fix! I'd close the ticket if it weren't already closed ;)

**Comment by yohanboniface** [comment]
Good to know! Thank you for the details, once we are able to reproduce a bug, 80% of the work for fixing it is done :)
