### ISSUE TITLE
Using a specific version of carto

### ISSUE THREAD

**Issue by pnorman** [kosmtik/kosmtik#43]
Different carto versions between production and development recently caused problems (gravitystorm/openstreetmap-carto#1294).

How would I install/run Kosmtik to make use of a specific version of carto?

**Comment by yohanboniface** [comment]
Have you tried `--mapnik-version`, which force a version of mapnik-reference to be used? Or you mean a specific version of the node package?

**Comment by pnorman** [comment]
carto, not mapnik. The issue we had was independent of mapnik version. `--mapnik-version` is wonderful for making sure we're not accidentally including features in master and not released 2.2.x.

Or, CartoCSS versions instead, but that's not versioned separately from carto.

**Comment by yohanboniface** [comment]
OK, I'm reading the thread Tilemill, and I can't say better than @springmeyer answer: version is managed by the package.json file, so changing it in there and reinstalling (npm install) will do the trick. But this could be an issue when git pulling again if the version has changed mainstream.

You can also just type `npm install carto@x.x.x` to have you own version without changing the source.

**Comment by pnorman** [comment]
> `npm install carto@x.x.x`

Within the kosmtik directory? And that will then override what's in package.json?

**Comment by yohanboniface** [comment]
yes and yes

**Comment by nebulon42** [comment]
I think at the moment there will not be a better way as the one mentioned. Closing this.
