### ISSUE TITLE
Carto reference

### ISSUE THREAD

**Issue by systemed** [kosmtik/kosmtik#44]
The online carto docs these days are [a bit rudimentary](https://github.com/mapbox/carto/blob/master/docs/latest.md) and really hard to browse.

It'd be good to have a Carto reference available within kosmtik (as it is within Tilemill), perhaps as a plugin.

**Comment by yohanboniface** [comment]
Yes, that's somewhere on my todolist (as a plugin), and then as the need raises I'll try to put it higher on the priorities :)

**Comment by yohanboniface** [comment]
@systemed pushed https://github.com/kosmtik/kosmtik-mapnik-reference just now.
It needs a bit more love, but it's yet installable, so if you wanna test and give feedback, please :)

**Comment by nebulon42** [comment]
Great addition!

**Comment by denics** [comment]
Thumb up!!! :+1:

**Comment by brunob** [comment]
Should we close this issue since carto reference plugin is alive ?

**Comment by yohanboniface** [comment]
Yep :)
