### ISSUE TITLE
local config option needs absolute path?

### ISSUE THREAD

**Issue by nebulon42** [kosmtik/kosmtik#56]
When I use the `--localconfig` option with a relative path (e.g. `../openstreetmap-carto.localconfig.js`) I get the output `[Local Config] Unable to load local config from ../openstreetmap-carto.localconfig.js`. If I use the absolute path (e.g. `~/path/to/openstreetmap-carto.localconfig.js`) this works as expected.

**Comment by yohanboniface** [comment]
Thanks for the report, I'll look at this asap (in a mission in Jordan right now).

**Comment by yohanboniface** [comment]
Pushed a fix that make absolute any relative path, but note that this will only work with Node 0.12 (while with older version we will have the old behaviour).
