### ISSUE TITLE
Blurry map on Full HD display in Firefox

### ISSUE THREAD

**Issue by nebulon42** [kosmtik/kosmtik#58]
I'm working on a Full HD display and the map in Kosmtik looks blurry while the map on osm.org looks perfectly crisp.

Ref: https://lists.openstreetmap.org/pipermail/dev/2015-April/028504.html

**Comment by nebulon42** [comment]
An interesting thing I discovered when using the map-compare plugin (great thing, by the way) that also the former crisp osm.org looked blurry. I then displayed one of my local tiles directly and it looked sharp too (the tile alone).

It seems that the leaflet display does some sort of modification to the tiles so that the look blurry. I will have a closer look.

**Comment by nebulon42** [comment]
Chromium is not affected, so changing the title. Might be a Leaflet issue.

**Comment by pnorman** [comment]
Double-check that you are not zoomed in at all.

**Comment by nebulon42** [comment]
I'm embarrassed to admit that you were right. Good catch. Have no idea when I did that. Sorry, closing this.
