### ISSUE TITLE
Cryptic error message on invalid localconfig JSON

### ISSUE THREAD

**Issue by pnorman** [kosmtik/kosmtik#70]
I had mistakenly saved the wrong file, and had an empty localconfig.json file
```
[Core] Loading config from /home/pnorman/.config/kosmtik.yml
[Core] Loading plugin from ../plugins/base-exporters/index.js
[Core] Loading plugin from ../plugins/hash/index.js
[Core] Loading plugin from ../plugins/local-config/index.js
[Core] Loading plugin from ../plugins/datasource-loader/index.js
[Core] Unable to load plugin kosmtik-map-compare MODULE_NOT_FOUND
[Core] Loading plugin from kosmtik-fetch-remote
[Core] Loading project from /home/pnorman/osm/HDM-CartoCSS/hdm.mml
[Core] PreviewServer started, you can browse http://0.0.0.0:6789

undefined:0

^
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at L.fromString (/usr/home/pnorman/osm/kosmtik/node_modules/json-localizer/index.js:71:46)
    at /usr/home/pnorman/osm/kosmtik/src/plugins/local-config/index.js:38:15
    at fs.js:272:14
    at Object.oncomplete (fs.js:108:15)
```

Edit: Fixed details

**Comment by yohanboniface** [comment]
Are you running on latest master?
I thought I fixed this some time ago (https://github.com/kosmtik/kosmtik/commit/9ad20b27511fa963d934a967f19621cf27d873c9 #60) and I'm not able to reproduce it (no error with an empty localconfig.js).

**Comment by pnorman** [comment]
> Are you running on latest master?

Ah, that'd be it. I'm using a 2.2 stylesheet, so haven't been tracking master

**Comment by yohanboniface** [comment]
When you upgrade kosmtik, remember to upgrade also the plugins (yeah, I need to make this easier ;) ).
Anyway, if you have the change to test with latest kosmtik to check if the issue is fixed, that would be helpful :)
