### ISSUE TITLE
Missing index.html

### ISSUE THREAD

**Issue by popkinj** [kosmtik/kosmtik#74]
Seems the index.html file is missing.
>Not Found: /home/user/kosmtik/node_modules/kosmtik/src/front/index.html

**Comment by yohanboniface** [comment]
How are you running kosmtik?

**Comment by popkinj** [comment]
Starting the server via command line:
```bash
iojs index.js serve
```
Then pointing my browser to:
>http://localhost:6789/

**Comment by yohanboniface** [comment]
> iojs index.js serve

You need to serve a project `iojs index.js serve myproject.mml (or .yml)`

If you want a project to test, you can use https://github.com/yohanboniface/thank-you-map

Plus, I've not used iojs yet myself, you may have issues :(

**Comment by popkinj** [comment]
Works great @yohanboniface 
Thanks for your help.

For the record... [iojs](https://iojs.org/en/index.html) has no problems with kosmtik. ☺

**Comment by yohanboniface** [comment]
Good to know, thanks :)
