### ISSUE TITLE
Super slow on debian jessie

### ISSUE THREAD

**Issue by cmyk** [kosmtik/kosmtik#84]
I installed everything on debian 8. And it's just super slow. Tiles start to appear after 3–5 minutes.
Any pointers, as to what it could be? Which log to look at? I testest some psql queries and they appeared normal.

**Comment by yohanboniface** [comment]
try a style without any psql request, and see if it's still slow

**Comment by cmyk** [comment]
you're right... any ideas why the queries could be that slow?
It's on a ibm M3 with 16 cores, SSDs and 20GB ram.

**Comment by cmyk** [comment]
It's weird. I have just Liechtenstein in the osm db and it's taking ages for tiles to render.
The more psql queries there are the slower. But psql has practically no load?
```
  PID USER      PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  Command
15453 osm        20   0 6192M 4479M 20508 S 99.8 21.9  2:08.78 kosmtik
15458 osm        20   0 6192M 4479M 20508 R 99.8 21.9  1:53.40 kosmtik
16414 osm        20   0 24156  3196  1396 R  0.0  0.0  0:00.23 htop
 2189 haproxy    20   0 31700  1932   672 S  0.0  0.0  0:16.91 /usr/sbin/haproxy -f /etc/haproxy/haproxy.cfg -D -p /var/run/haproxy.pid
12483 root       20   0  258M  1540   872 S  0.0  0.0  0:01.75 /usr/sbin/rsyslogd
14748 postgres   20   0 82728  2096   464 S  0.0  0.0  0:00.12 postgres: stats collector process
11248 osm        20   0 82648  2048  1152 S  0.0  0.0  0:00.22 sshd: osm@pts/2
```

**Comment by yohanboniface** [comment]
Is this same style slow on an other computer/server?

**Comment by pnorman** [comment]
What is a PostGIS query that is slow?

**Comment by cmyk** [comment]
Sorry, Yohan, it seems to be the contours db that's acting up after a hard update from postgis 1.5 to 2.1. The osm data seems to load as expected.
