### ISSUE TITLE
Getting started problem

### ISSUE THREAD

**Issue by lsces** [kosmtik/kosmtik#86]
What am I missing? Have cloned a copy of kosmtik but running 'npm install' is giving me 304 errors against each module and not creating node_modules.
node v0.10.5
npm v1.2.18
There is no package.json in the downloaded package, only index.js

**Comment by yohanboniface** [comment]
Very weird.

How exactly have you cloned the repo?

(Sorry for the late answer, I was offline.)

**Comment by yohanboniface** [comment]
Closing, please reopen if you still need help.
