### ISSUE TITLE
Remote connection to the PreviewServer

### ISSUE THREAD

**Issue by flemmens** [kosmtik/kosmtik#89]
I am not sure if this is the right place to ask the question... I am new to Kosmtik, everything is installed on my server and works fine, but how can I setup a remote access to the PreviewServer ? Once launched, I have a message saying "PreviewServer started, you can browse http://127.0.0.1:6789", but when I try to connect to my server from a distant location (http://MyServerIP:6789), it does not work. Is there any config file where I can set up / allow a remote connection (something like listenHost=0.0.0.0) ? Thanks !

**Comment by yohanboniface** [comment]
you can pass `--host 0.0.0.0` to the command line:

    node index.js serve path/to/project.yml --host 0.0.0.0

Also

    node index.js serve --help

:)

**Comment by flemmens** [comment]
That was quick :) Thanks !
